services:
  backend:
    build: .
    environment:
      DB_HOST: database
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - work_network

  database:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - work_network

volumes:
  postgres_data:

networks:
  work_network:
    driver: bridge