[project]
name = "chatbilling"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=4.3.0",
    "langchain>=0.3.26",
    "langchain-openai>=0.3.28",
    "passlib>=1.7.4",
]
